[[servers]]
  name = "filesystem"
  package = "npx::@modelcontextprotocol/server-filesystem@latest"
  tools = ["read_file", "read_multiple_files", "edit_file", "list_directory", "search_files", "get_file_info", "write_file", "create_directory", "directory_tree", "move_file", "list_allowed_directories"]
