version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.simple
    ports:
      - "8000:8000"
    environment:
      - MCPD_ENABLED=false  # For initial testing without MCPD
      - ALLOWED_ORIGINS=http://localhost:5173,http://localhost:5174,http://localhost:3000
      - CLOUD_MODE=true
    volumes:
      - ./backend:/app  # For development
      - mcpd-data:/data
    networks:
      - mcp-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5174:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - VITE_WS_BASE_URL=ws://localhost:8000
    networks:
      - mcp-network
    depends_on:
      - backend

networks:
  mcp-network:

volumes:
  mcpd-data: